/*
 * SInput IMU Example
 *
 * Demonstrates gyroscope and accelerometer output over SInput.
 * Uses simulated sine/cosine data so it works on any ESP32 board
 * without additional hardware.
 *
 * To use a real IMU (e.g. MPU6050), uncomment the Wire/I2C code below
 * and comment out the simulated data section.
 *
 * The IMU timestamp is auto-generated by sendSInputReport().
 *
 * Hardware for real IMU (MPU6050):
 *   ESP32 GPIO 21 (SDA) --> MPU6050 SDA
 *   ESP32 GPIO 22 (SCL) --> MPU6050 SCL
 *   MPU6050 VCC --> 3.3V
 *   MPU6050 GND --> GND
 */

#include <BleGamepad.h>
// #include <Wire.h> // Uncomment for real MPU6050 sensor

BleGamepad bleGamepad;
BleGamepadConfiguration config;

void setup()
{
  Serial.begin(115200);
  Serial.println("Starting SInput IMU...");

  // Configure as SInput device with IMU enabled
  config.setAutoReport(false);
  config.setGamepadMode(GamepadMode::SInput);
  config.setEnableSInputIMU(true);

  bleGamepad.begin(&config);

  // Uncomment for real MPU6050 sensor
  // Wire.begin();
  // Wire.beginTransmission(0x68);
  // Wire.write(0x6B);
  // Wire.write(0x00); // Wake up the MPU6050
  // Wire.endTransmission(true);
}

void loop()
{
  if (bleGamepad.isConnected())
  {
    unsigned long now = millis();
    float t = now / 1000.0; // Time in seconds

    // --- Simulated IMU data ---
    // Gyroscope: degrees per second (+/- 2000 dps range)
    int16_t gyroX = (int16_t)(sin(t * 2.0) * 2000);
    int16_t gyroY = (int16_t)(cos(t * 3.0) * 2000);
    int16_t gyroZ = (int16_t)(sin(t * 1.5) * 2000);

    // Accelerometer: scaled g force (+/- 8g range)
    int16_t accelX = (int16_t)(sin(t * 0.5) * 8000);
    int16_t accelY = (int16_t)(cos(t * 0.7) * 8000);
    int16_t accelZ = (int16_t)(sin(t * 0.3 + 1.57) * 8000); // ~90 degree phase offset

    // Uncomment for real MPU6050 data
    // Wire.beginTransmission(0x68);
    // Wire.write(0x3B);
    // Wire.endTransmission(false);
    // Wire.requestFrom((uint8_t)0x68, (uint8_t)14, (uint8_t)true);
    // int16_t accelX = Wire.read() << 8 | Wire.read();
    // int16_t accelY = Wire.read() << 8 | Wire.read();
    // int16_t accelZ = Wire.read() << 8 | Wire.read();
    // Wire.read(); Wire.read(); // Skip temperature
    // int16_t gyroX = Wire.read() << 8 | Wire.read();
    // int16_t gyroY = Wire.read() << 8 | Wire.read();
    // int16_t gyroZ = Wire.read() << 8 | Wire.read();

    bleGamepad.setGyroscope(gyroX, gyroY, gyroZ);
    bleGamepad.setAccelerometer(accelX, accelY, accelZ);
    bleGamepad.sendReport();

    // Print IMU values at ~10Hz to avoid flooding Serial
    static unsigned long lastPrintTime = 0;
    if (now - lastPrintTime >= 100)
    {
      lastPrintTime = now;
      Serial.printf("Gyro: %6d %6d %6d  Accel: %6d %6d %6d\n",
                    gyroX, gyroY, gyroZ, accelX, accelY, accelZ);
    }

    // Toggle BUTTON_1 every 1 second as a heartbeat,
    // so the host knows the device is alive and sending input reports
    static bool buttonPressed = false;
    static unsigned long lastToggleTime = 0;

    if (millis() - lastToggleTime >= 1000)
    {
      lastToggleTime = millis();

      if (buttonPressed)
      {
        bleGamepad.release(BUTTON_1);
        buttonPressed = false;
      }
      else
      {
        bleGamepad.press(BUTTON_1);
        buttonPressed = true;
      }

      bleGamepad.sendReport();
    }

    delay(5); // ~200Hz update rate for IMU data
  }
}
